//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstoqueCliente.ServicoEstoque
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://projetoavaliativo.dm113/02", ConfigurationName="EstoqueCliente.ServicoEstoque.IServicoEstoqueV2")]
    public interface IServicoEstoqueV2
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IServicoEstoqueV2/adicionarEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IServicoEstoqueV2/adicionarEstoqueResponse")]
        bool adicionarEstoque(string numeroProduto, int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IServicoEstoqueV2/adicionarEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IServicoEstoqueV2/adicionarEstoqueResponse")]
        System.Threading.Tasks.Task<bool> adicionarEstoqueAsync(string numeroProduto, int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IServicoEstoqueV2/removerEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IServicoEstoqueV2/removerEstoqueResponse")]
        bool removerEstoque(string numeroProduto, int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IServicoEstoqueV2/removerEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IServicoEstoqueV2/removerEstoqueResponse")]
        System.Threading.Tasks.Task<bool> removerEstoqueAsync(string numeroProduto, int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IServicoEstoqueV2/consultarEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IServicoEstoqueV2/consultarEstoqueResponse")]
        int consultarEstoque(string numeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IServicoEstoqueV2/consultarEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IServicoEstoqueV2/consultarEstoqueResponse")]
        System.Threading.Tasks.Task<int> consultarEstoqueAsync(string numeroProduto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoEstoqueV2Channel : EstoqueCliente.ServicoEstoque.IServicoEstoqueV2, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoEstoqueV2Client : System.ServiceModel.ClientBase<EstoqueCliente.ServicoEstoque.IServicoEstoqueV2>, EstoqueCliente.ServicoEstoque.IServicoEstoqueV2
    {
        
        public ServicoEstoqueV2Client()
        {
        }
        
        public ServicoEstoqueV2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ServicoEstoqueV2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ServicoEstoqueV2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ServicoEstoqueV2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool adicionarEstoque(string numeroProduto, int quantidade)
        {
            return base.Channel.adicionarEstoque(numeroProduto, quantidade);
        }
        
        public System.Threading.Tasks.Task<bool> adicionarEstoqueAsync(string numeroProduto, int quantidade)
        {
            return base.Channel.adicionarEstoqueAsync(numeroProduto, quantidade);
        }
        
        public bool removerEstoque(string numeroProduto, int quantidade)
        {
            return base.Channel.removerEstoque(numeroProduto, quantidade);
        }
        
        public System.Threading.Tasks.Task<bool> removerEstoqueAsync(string numeroProduto, int quantidade)
        {
            return base.Channel.removerEstoqueAsync(numeroProduto, quantidade);
        }
        
        public int consultarEstoque(string numeroProduto)
        {
            return base.Channel.consultarEstoque(numeroProduto);
        }
        
        public System.Threading.Tasks.Task<int> consultarEstoqueAsync(string numeroProduto)
        {
            return base.Channel.consultarEstoqueAsync(numeroProduto);
        }
    }
}
